[build]
  publish = "docs"
  command = "cd io-burgard && npm install && npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://identity.netlify.com; img-src 'self' data: https://unpkg.com https://identity.netlify.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://identity.netlify.com; style-src 'self' 'unsafe-inline' https://unpkg.com; connect-src 'self' https://api.github.com https://identity.netlify.com; frame-src https://identity.netlify.com;"
