backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

i18n:
  structure: multiple_folders
  locales: [fr, en]
  default_locale: fr

collections:
  - name: "pages"
    label: "Pages du site"
    files:
      - name: "home"
        label: "Page d'accueil"
        file: "content/settings/home.yml"
        fields:
          - label: "Liens d'actualité"
            name: "announcements"
            widget: "list"
            required: false
            fields:
              - { label: "Texte", name: "text", widget: "string" }
              - { label: "Lien", name: "url", widget: "string", required: false }
          - label: "Images de la page d'accueil"
            name: "images"
            widget: "list"
            required: false
            field: { label: "Image", name: "image", widget: "image" }
      - name: "bio_fr"
        label: "Bio française"
        file: "content/settings/bio.fr.md"
        fields:
          - { label: "Texte", name: "body", widget: "markdown" }
      - name: "bio_en"
        label: "Bio anglaise"
        file: "content/settings/bio.en.md"
        fields:
          - { label: "Texte", name: "body", widget: "markdown" }
      - name: "portfolio"
        label: "Portfolio PDF"
        file: "content/settings/portfolio.yml"
        fields:
          - { label: "PDF du portfolio", name: "portfolio", widget: "file" }
  - name: "projects"
    label: "Projets"
    label_singular: "Projet"
    folder: "content/projects"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Titre", name: "title", widget: "string", i18n: true }
      - { label: "Date", name: "date", widget: "datetime", i18n: "duplicate", required: false }
      - label: "Images"
        name: "images"
        widget: "list"
        i18n: "duplicate"
        required: false
        field: { label: "Image", name: "image", widget: "image" }
      - { label: "Texte", name: "body", widget: "markdown", i18n: true, required: false }
